sudo: required
dist: xenial
language: rust

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-server-dev-11


matrix:
  include:
    # parallel builds for tests
    - rust: stable
      env: NAME=stable
           PG_BASE_INCLUDE=$(pg_config --includedir)
           PG_INCLUDE_PATH=${PG_BASE_INCLUDE}/11/server
           RUSTFLAGS="-C link-arg=-undefineddynamic_lookup"
           RUST_BACKTRACE=full
      before_install:
        - rustup component add rustfmt
      script:
        - cargo test

        # macos
    - os: osx
      rust: stable
      env: NAME=macOS
           PG_INCLUDE_PATH=/usr/local/Cellar/postgresql/11.1/include/server
           RUSTFLAGS="-C link-arg=-undefineddynamic_lookup"
           RUST_BACKTRACE=full
      before_install:
        - brew upgrade postgresql || brew install postgres
        - rustup component add rustfmt
      script: 
        - cargo test

    # clippy
    - rust: stable
      env: NAME=clippy
           PG_BASE_INCLUDE=$(pg_config --includedir)
           PG_INCLUDE_PATH=${PG_BASE_INCLUDE}/11/server
           RUSTFLAGS="-C link-arg=-undefineddynamic_lookup"
           RUST_BACKTRACE=full
      before_install:
        - rustup component add clippy
      script:
        - cargo clippy

script:
  - cargo test

#after_success: scripts/run_kcov.sh
